# 前言

大多数错误没有严重到需要程序完全停止的程度。有时，当函数失败时，这是由于您可以轻松解释和响应的原因。例如，如果您尝试打开一个文件，但该操作失败，因为该文件不存在，您可能希望创建该文件，而不是终止进程。



# 内容

这里我们就考虑到在最开始的时候，我们在猜谜游戏中使用`Result` 枚举被定义为具有两个成员，`Ok` 和 `Err`，如下所示：

```rust
#![allow(unused)]
fn main() {
  enum Result<T, E> {
      Ok(T),
      Err(E),
  }
}
```

`T` 和 `E` 是泛型类型参数，您现在需要知道的是，`T` 表示在 `Ok`成员中成功案例中将返回的值的类型，`E` 表示在 `Err` 成员中失败时将返回的错误类型。因为 `Result` 有这些泛型类型参数，所以我们可以在许多不同的情况下使用 `Result` 类型和它定义的函数，在这些情况下，我们想要返回的成功值和错误值可能不同。

让我们调用一个返回 `Result` 值的函数，因为该函数可能会失败。如下所示，我们尝试打开一个文件。

```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");
}
```



